---
- name: Enable features on Spine
  hosts: spine
  connection: local
  gather_facts: no
  strategy: free
  
  roles:
    - common
    - spine
  
  vars:
    playbook_name: "Enable features on Spine"

  tasks:
    - block:
        - name: Ensure OSPF is enabled
          nxos_feature:
            feature: ospf
            state: enabled
            username: "{{ nxapi['username'] }}"
            password: "{{ nxapi['password'] }}"
            transport: "{{ nxapi['transport'] }}"
          tags:
            - enable_feature_ospf
        - name: Ensure BGP is enabled
          nxos_feature:
            feature: bgp
            state: enabled
            username: "{{ nxapi['username'] }}"
            password: "{{ nxapi['password'] }}"
            transport: "{{ nxapi['transport'] }}"
          tags:
            - enable_feature_bgp
        - name: Ensure PIM is enabled
          nxos_feature:
            feature: pim
            state: enabled
            username: "{{ nxapi['username'] }}"
            password: "{{ nxapi['password'] }}"
            transport: "{{ nxapi['transport'] }}"
          tags:
            - enable_feature_pim
        - name: Ensure VRRPv3 is enabled
          nxos_feature:
            feature: vrrpv3
            state: enabled
            username: "{{ nxapi['username'] }}"
            password: "{{ nxapi['password'] }}"
            transport: "{{ nxapi['transport'] }}"
          tags:
            - enable_feature_vrrpv3
        - name: Ensure BFD is enabled
          nxos_feature:
            feature: bfd
            state: enabled
            username: "{{ nxapi['username'] }}"
            password: "{{ nxapi['password'] }}"
            transport: "{{ nxapi['transport'] }}"
          tags:
            - enable_feature_bfd
        - name: Ensure interface-vlan is enabled
          nxos_feature:
            feature: interface-vlan
            state: enabled
            username: "{{ nxapi['username'] }}"
            password: "{{ nxapi['password'] }}"
            transport: "{{ nxapi['transport'] }}"
          tags:
            - enable_feature_interface-vlan
        - name: Ensure scp-server is enabled
          nxos_feature:
            feature: scp-server
            state: enabled
            username: "{{ nxapi['username'] }}"
            password: "{{ nxapi['password'] }}"
            transport: "{{ nxapi['transport'] }}"
          tags:
            - enable_feature_scp-server
        - name: Notify on success
          set_fact:
            trigger_msg: True
            send_msg: "{{ playbook_name }} -  success configure on {{ inventory_hostname }}"
          changed_when: True
          notify: notify using spark
      ignore_errors: False
      rescue:
        - set_fact:
            trigger_msg: True
            send_msg: "{{ playbook_name }} -  error configure on {{ inventory_hostname }}"
          changed_when: True          
          notify: notify using spark
...
